name: 'deploy'

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'docs/'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'docs/'
    
jobs:
  doit: 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy Package to Github NuGet
      run: .\test.cmd
      env: 
        GITHUB_PACKAGE_TOKEN: ${{ secrets.NUGET_KEY }}